<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Jackalope.Tack.Search</PackageId>
    <RootNamespace>Tack.Search</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeStructure.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jackalope.Tack.Core\Jackalope.Tack.Core.csproj" />
  </ItemGroup>

</Project>
